select * from customer 
--q1).what is the total revenue generated by male vs female
select gender,sum(purchase_amount) as revenue 
from customer 
group by gender
--insight:male customers generated more revenue than the females
--q2.which customers used a discount but still spend more than the average purchase amount
select customer_id,purchase_amount 
from customer 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)
--insight:839 customers are purchased more than the average purchase amount
--q3).which are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating::numeric),2) as "average product rating" 
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5
--Gloves,Sandals,Boots,Hat,Skirt have the highest rating respectively
--q4).compare the average purchase amounts between standard and express shipping
select shipping_type,round(avg(purchase_amount),2)as "average purchase amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg(purchase_amount) desc
--experess shipping has more average purchase amount compared to standard shipping 
--q5).do subscribed customers spend more?compare average spend and total revenue between subscribers and non subscribers,
select subscription_status,count(customer_id)as "total_customer",round(avg(purchase_amount)) as "average spend",round(sum(purchase_amount)) as "total revenue"
from customer
group by subscription_status
--the non subscribers has slightly more average spend and they generated more total revenue compared to subscribers
--q6).which 5 products have the highest percentage of purchases with discounts applied
select item_purchased ,
round(100 * sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*), 2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5
--50% of the time the hat is sold with discount,sneakers-49%,coat-49%,sweater-48%,pants-47% respectively
--q7).segment customers into new(1),returning(2-10) and loyal(10+ purchases) based on their total number of previous purchases and show the count of segment
with customer_type as(
select customer_id,previous_purchases,
case 
    when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as totalnumber_of_customer
from customer_type
group by customer_segment
order by totalnumber_of_customer desc
--loyal customers are 3116 ,returning are 701,new 83
--q8).what are the top 3 most purchased products in each category
with item_count as(
select category,item_purchased,count(customer_id)as total_orders,
row_number()over(partition by category order by count(customer_id)desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3
--on accessories-jewlery,clothing-blouse,footwear-sandals,outerwear-jacket are the most sold products in each category
--q9).are customers who are repeat buyers(more than 5 previous purchases)also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status
--the repeat buyers are more belongs to non-subscribers
--q10).what is the revenue contribution of each age group
select age_group,sum(purchase_amount)as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc
--young adult has the more revenue contribution